export enum NotificationType {
  TEAM_INVITE = 1,
  TEAM_JOINED = 2,
  PROJECT_CREATED = 3,
  PROJECT_UPDATED = 4,
  PROJECT_ARCHIVED = 5,
  TASK_CREATED = 6,
  TASK_ASSIGNED = 7,
  TASK_STATUS_CHANGED = 8,
  TASK_COMPLETED = 9,
  CHECKLIST_COMPLETED = 10,
  MENTION = 11,
}
